# Generated by Django 3.2 on 2022-08-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_user_profile'),
    ]

    operations = [
    ]
